version: '3.8'
services:
  api-gateway:
    build: .
    working_dir: /app/packages/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://user:pass@mongodb:27017/db
      - MONGO_URI=mongodb://mongodb:27017/db
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongodb
      - redis
      - kafka
  user-service:
    build: .
    working_dir: /app/packages/user-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongodb
      - redis
      - kafka
  notification-service:
    build: .
    working_dir: /app/packages/notification-service
    environment:
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - kafka
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  kafka:
    image: bitnami/kafka:3.6.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    ports:
      - "2181:2181"
volumes:
  mongo-data:
  redis-data:
