apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: node:20-alpine
          command: ["npm", "run", "dev"]
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/db"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: KAFKA_BROKER
              value: "kafka:9092"
