name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, user-service, notification-service]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build ${{ matrix.service }}
        run: |
          cd packages/${{ matrix.service }}
          npm run build
      - name: Lint ${{ matrix.service }}
        run: |
          cd packages/${{ matrix.service }}
          npm run lint
      - name: Test ${{ matrix.service }}
        run: |
          cd packages/${{ matrix.service }}
          npm test
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: docker-compose build
